create table users (
    id int primary key generated by default as identity ,
    nickname varchar(50) not null ,
    email varchar(50) not null unique ,
    password varchar(256) not null
);

create table sessions (
    id bigint primary key generated by default as identity ,
    issued_at timestamp with time zone not null ,
    expired_at timestamp with time zone not null ,
    enable bool not null default false,
    user_id int not null references users("id") on delete cascade
);
